// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Placica.Core.Infraestructure.Data.Context;

namespace Placica.Core.WebAPI.Data.SqlliteMigrations
{
    [DbContext(typeof(PlacicaContext))]
    [Migration("20200717182012_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Data")
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Placica.Core.Library.Entities.Calificacion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<long>("ParametroDetalleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParametroDetalleId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Categoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TipoIdentificacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoIdentificacionId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color3")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsables")
                        .HasColumnType("TEXT");

                    b.Property<string>("SitioWeb")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefonos")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TipoId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TipoIdentificacionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.HasIndex("TipoIdentificacionId");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.EmpresaCategoria", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("EmpresaCategorias");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Parametro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.ParametroDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ParametroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParametroId");

                    b.ToTable("ParametroDetalles");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Pedido", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CliApellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliDireccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliIdentificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliNombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliTelefono")
                        .HasColumnType("TEXT");

                    b.Property<string>("CliTipoIdentificacion")
                        .HasColumnType("TEXT");

                    b.Property<long>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpDireccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpIdentificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpRazonSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpResponsables")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpTelefonos")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmpTipoIdentificacion")
                        .HasColumnType("TEXT");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Envio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaDoc")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Impuesto")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.PedidoDetalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<long>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PedidoDetalles");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Producto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModify")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<long>("EmpresaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imagen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presentacion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserCreate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModify")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Calificacion", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.ParametroDetalle", "ParametroDetalle")
                        .WithMany()
                        .HasForeignKey("ParametroDetalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Placica.Core.Library.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Cliente", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.ParametroDetalle", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionId");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Empresa", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.Parametro", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoId");

                    b.HasOne("Placica.Core.Library.Entities.ParametroDetalle", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionId");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.EmpresaCategoria", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Placica.Core.Library.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.ParametroDetalle", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.Parametro", null)
                        .WithMany("ParamDetalle")
                        .HasForeignKey("ParametroId");
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Pedido", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Placica.Core.Library.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.PedidoDetalle", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.Pedido", "Pedido")
                        .WithMany("PedidoDetalles")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Placica.Core.Library.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Placica.Core.Library.Entities.Producto", b =>
                {
                    b.HasOne("Placica.Core.Library.Entities.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Placica.Core.Library.Entities.Empresa", "Empresa")
                        .WithMany("Productos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
